apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: microservices:1.0
          command: ["./movies"]
          ports:
            - containerPort: 8080