kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: francecentral-2
nodes:
  - role: control-plane
    labels:
      zone: francecentral-2
  - role: worker
    labels:
      zone: francecentral-2
  - role: worker
    labels:
      zone: francecentral-2
  - role: worker
    labels:
      zone: francecentral-2