apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: microservices:1.0
          command: ["./books"]
          ports:
            - containerPort: 8080